global:
    scrape_interval: 1s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['10.3.141.1:9090']
    - job_name: 'bmp'
      static_configs:
          - targets: ['10.3.141.20:80']
            labels:
                group: 'potager01'